name: Tests with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install packages
        run: yarn --immutable
      - name: Build packages
        run: yarn build
      - name: Check for circular dependencies
        run: yarn check-circular-deps
      - name: Test with coverage
        run: yarn coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
